Added Wazuh Cloud info and updated nav instructions.
JupiterOne/graph-wazuh pull request #62
Opened 2023-03-02 15:07 UTC by janettelynch

# Description

Thank you for contributing to a JupiterOne integration!

Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context. List any dependencies that are required
for this change.

## Summary

## Type of change

Please leave any irrelevant options unchecked.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## Checklist

### General Development Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### Integration Development Checklist:

Please leave any irrelevant options unchecked.

- [ ] I have checked for additional permissions required to call any new API
      endpoints, and have documented any additional permissions in
      `jupiterone.md`, where necessary.
- [ ] My changes properly paginate the target service provider's API
- [ ] My changes properly handle rate limiting of the target service provider's
      API
- [ ] My new integration step is instrumented to execute in the correct order
      using `dependsOn`
- [ ] I have referred to the
      [JupiterOne data model](https://github.com/JupiterOne/data-model/tree/main/src/schemas)
      to ensure that any new entities/relationships, and relevant properties,
      match the recommended model for this class of data
- [ ] I have updated the `CHANGELOG.md` file to describe my changes
- [ ] When changes include modifications to existing graph data ingestion, I've
      reviewed all existing managed questions referencing the entities,
      relationships, and their property names, to ensure those questions still
      function with my changes.

2023-03-02 16:45 UTC, mdaum requested changes

2023-03-02 16:45 UTC, mdaum commented on docs/jupiterone.md
> +- 18.219.33.157
let's get rid of these IPs. We have a diff set for each production env, and we will just have customers reach out to us for the right set to whitelist.

2023-03-02 16:45 UTC, mdaum commented on docs/jupiterone.md
> +If you are using Wazuh Cloud, contact Wazuh Support to make changes to your Wazuh
Let's change this to:

> If you are using Wazuh Cloud, please contact J1 support, as we will need to provide you a list of IPs for Wazuh to whitelist. After getting that list from us, you will need to contact Wazuh Support to make changes to your Wazuh....(the rest of what you already have).

2023-03-02 16:45 UTC, mdaum commented on docs/jupiterone.md
> +following format: https://${wauzhCloudEnvId}.cloud.wazuh.com/api/wazuh.
let's put back ticks around the template uri:

`https://${wauzhCloudEnvId}.cloud.wazuh.com/api/wazuh`
and drop the period at the end, as many will copy/paste this.

2023-03-03 12:34 UTC, janettelynch commented
@mdaum Could you review and approve? Thanks!

2023-03-03 16:59 UTC, VDubber submitted a review, later dismissed

2023-03-06 18:03 UTC, mdaum approved these changes

2023-03-06 18:03 UTC, merged